### ISSUE TITLE
Button & select tweaks

### ISSUE THREAD

**Issue by ajb** [dobtco/dvl-core#77]
Made these changes in `feature/project-teams-mvp`, they didn't turn out to be necessary for that branch, but we might want to consider merging them anyway:

```css
.button {
  line-height: normal;
}

.styled_select_wrapper {
  vertical-align: top;
}
```
